import React, { useState } from 'react';
import Head from 'next/head' ;

import { BsLinkedin , BsGithub} from "react-icons/bs";
import {IoIosCloudyNight} from "react-icons/io";
import { DiGit,DiHtml5,DiJsBadge,DiLinux,DiNodejs,DiPostgresql,DiReact} from "react-icons/di";

import Image from 'next/image';
import Avatar from '../public/myAvatar sinfondo.png';
import Movies from '../public/movies.png';
import Vaca from '../public/vaca-chocha.png';
import Inmobiliaria from '../public/inmo.png';
import Farmacia from '../public/farmacia.png';

import Logo from '../public/logo1.png';

import  Node  from '../public/images/node-js-logo.jpg';
import  Express  from '../public/images/express-logo.png';
import Git from '../public/images/git-logo.png';
import Github from '../public/images/github-logo.png';
import Js from '../public/images/js-logo.png';
import Linux from '../public/images/linux-logo.png';
import Mongo from '../public/images/mongo-logo.png';
import Postgres from '../public/images/postgres-logo.png';
import ReactLogo from '../public/images/react-logo.png';


export default function Home() {
  
  const [darkMode,setDarkMode] = useState(false);
  const [lightMode,setLightMode] = useState(false);

  return (
    <>
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Portfolio Alejandro Ramos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/portfolio.svg" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-800'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <Image src={Logo} className='cursor-pointer w-36 h-24'/>
            <ul className='flex items-center'>
              <li>
                <IoIosCloudyNight onClick={()=>setDarkMode(!darkMode)} className='cursor-pointer text-3xl'/>
              </li>
              <li>
                <a href='https://drive.google.com/file/d/1S2QF2Bz7mYWqRT28bAI1NFRL_pdcjIOJ/view?usp=share_link' download >
                  <button className='bg-cyan-300 text-black px-8 py-5 rounded-md ml-5'>Contáctame</button>
                </a>       
              </li> 
              <li>
                <a href='https://drive.google.com/file/d/1S2QF2Bz7mYWqRT28bAI1NFRL_pdcjIOJ/view?usp=share_link' download >
                  <button className='bg-cyan-300 text-black px-8 py-5 rounded-md ml-5'>Ver mi CV</button>
                </a>       
              </li> 
            </ul>  
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-4xl py-2 text-teal-500 font-medium md:text-6xl'>Alejandro Ramos</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Desarrollador Full Stack</h3>
            <p className='text-md py-5 leading-8 text-gray-600 md:text-xl'>Soy un programador nacido y criado en Ushuaia. De joven me interesé por la Informática y
            la Programación, pasando por educación secundaria y universidad. La vida me llevo a trabajar varios años en fábrica de electrodómesticos, decidí volver a mis raíces
            e ingresé a un bootcamp en JavaScript brindado por Plataforma 5.<br />Sigo formándome día a día para alcanzar mis metas como desarrollador de software.</p>
          </div>
          <div className='text-6xl flex justify-center gap-16 py-3 text-gray-700'>
            <BsLinkedin className='cursor-pointer' target='_blank' onClick={event =>  window.location.href='https://www.linkedin.com/in/alejandro-ramos-/'}/>
            <BsGithub className='cursor-pointer' target='_blank' onClick={event =>  window.location.href='https://github.com/ale336'}/>
          </div>
          <div className='relative mx-auto my-8 bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={Avatar} alt="avatar"  />
          </div>
        </section>
        <div className=' lg:flex text-2xl text-center gap-12 md:px-20'>
          <div>
            <Image src={Node} alt="node" className=' w-36 h-28'/>
            <h2 className='p-4'>Node Js</h2>
          </div>
          <div>
            <Image src={Express} alt="express" className='w-28 h-28'/>
            <h2 className='p-4'>Express Js</h2>
          </div>
          <div>
            <Image src={Git} alt="git" className=' w-36 h-28'/>
            <h2 className='p-4'>Git</h2>
          </div>
          <div>
            <Image src={Github} alt="github" className='w-28 h-28'/>
            <h2 className='p-4'>GitHub</h2>
          </div>
          <div>
            <Image src={Js} alt="js" className='w-28 h-28'/>
            <h2 className='p-4'>JavaScript</h2>
          </div>
          <div>
            <Image src={Linux} alt="linux" className='w-36 h-28'/>
            <h2 className='p-4'>Linux</h2>
          </div>
          <div>
            <Image src={Mongo} alt="mongo" className='w-28 h-28'/>
            <h2 className='p-4'>Mongo DB</h2>
          </div>
          <div>
            <Image src={Postgres} alt="postgres" className='w-28 h-28'/>
            <h2 className='p-4'>PostgreSQL</h2>
          </div>
          <div>
            <Image src={ReactLogo} alt="react" className=' w-40 h-28'/>
            <h2 className='p-4'>React Js</h2>
          </div>
        </div>
          
          {/* <h3 className='text-3xl py-1'>Servivios que ofrecemos</h3>
          <p className='text-md py-2 leading-8 text-gray-700'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor 
                <span className='text-teal-700'> incididunt </span>ut labore et dolore <span className='text-teal-700'>magna aliqua</span>. Ut enim ad minim 
                veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit 
                in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
          </p>
          <p className='text-md py-2 leading-8 text-gray-700'> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.</p> */}
        <div className='text-center'>
          <h2 className='text-blue-500 text-5xl font-bold'>PROYECTOS</h2>
        </div>
        <div className='lg:flex gap-10'>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
            <Image src={Farmacia} alt="App Pharmacy" width={190} height={140}/>
            <h3 className='text-lg font-medium pt-8 pb-2'>E-commerce Farmacia</h3>
            <p className='py-2'>Breve descripcion de la aplicacion sin mencionar las tecnologias</p>
            <div className=' mt-12 lg:flex gap-24 md:mt-10'>
              <a href='https://pharmacy-mern.onrender.com/' target='_blank' className='btn text-black px-2 py-2 border-4 border-blue-600 rounded-md'>Deploy</a>
              <a href='https://github.com/No-Country/C8-65-FT-MERN' target='_blank' className='btn text-black px-2 py-2 border-4 border-blue-600 rounded-md'>GitHub</a>
            </div>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
            <Image src={Vaca} alt="App Vaca" width={195} height={170}/>
            <h3 className='text-lg font-medium pt-8 pb-2'>E-commerce Dietética "Vaca Chocha"</h3>
            <p className='py-2'>Breve descripcion de la aplicacion sin mencionar las tecnologias</p>
            <div className=' mt-10 lg:flex gap-24'>
              <a href='#' className='btn text-black px-2 py-2 border-4 border-blue-600 rounded-md'>Deploy</a>
              <a href='https://github.com/ale336/La-Vaca-Chocha' className='btn text-black px-2 py-2 border-4 border-blue-600 rounded-md'>GitHub</a>
            </div>
          </div>
          
          <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
            <Image src={Inmobiliaria} alt="App Inmobiliaria" width={400} height={500}/>
            <h3 className='text-lg font-medium pt-8 pb-2'>Inmobiliaria Mejor Vivir</h3>
            <p className='py-2'>Breve descripcion de la aplicacion sin mencionar las tecnologias</p>
            <div className=' mt-16 lg:flex gap-24'>
              <a href='#' className='btn text-black px-2 py-2 border-4 border-blue-600 rounded-md'>Deploy</a>
              <a href='https://github.com/ale336/InmoMejorVivir' className='btn text-black px-2 py-2 border-4 border-blue-600 rounded-md'>GitHub</a>
            </div>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
            <Image src={Movies} alt="App Pelis" width={250} height={200} />
            <h3 className='text-lg font-medium pt-8 pb-2'>Movie App</h3>
            <p className='py-2'>Breve descripcion de la aplicacion sin mencionar las tecnologias</p>
            <div className=' mt-20 lg:flex gap-24'>
              <a href='#' className='btn text-black px-2 py-2 border-4 border-blue-600 rounded-md'>Deploy</a>
              <a href='#' className='btn text-black px-2 py-2 border-4 border-blue-600 rounded-md'>GitHub</a>
            </div>
          </div>

        </div>

        <div class="container mx-auto my-20 w-1/3 border border-blue-500 bg-white">
        <div class="p-5 space-y-5 shadow-xl">
        <h4 class="text-center text-3xl">Contáctame</h4>
        <form>
        <div class="grid grid-cols-2 gap-5">
          <input
            type="text"
            class="border border-gray-500 px-4 py-2 focus:outline-none focus:border-blue-500 col-span-2"
            placeholder="Nombre"
          />
          <input
            type="email"
            class="border border-gray-500 px-4 py-2 focus:outline-none focus:border-blue-500 col-span-2"
            placeholder="Email"
          />
          <textarea
            cols="10"
            rows="5"
            class="border border-gray-500 px-4 py-2 focus:outline-none focus:border-blue-500 col-span-2"
            placeholder="Escribí tu mensaje..."
          ></textarea>
        </div>
        <input
          type="submit"
          value="Enviar"
          class="focus:outline-none mt-5 bg-blue-500 px-4 py-2 text-white font-bold w-full"
        />
      </form>
  </div>
</div>
      </main>
    </div>
    </>
  )
}
