import React from 'react';
import Head from 'next/head' ;
import { BsLinkedin , BsGithub} from "react-icons/bs";
import { GoFile  } from "react-icons/go";
import Image from 'next/image';
import Avatar from '../public/myAvatar sinfondo.png';
import Movies from '../public/movies.png';
import Vaca from '../public/vaca-chocha.png';
import Inmobiliaria from '../public/inmo.png';


export default function Home() {
  return (
    <>
    <div>
      <Head>
        <title>Portfolio Alejandro Ramos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/portfolio.svg" />
      </Head>

      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl text-sky-700 font-burtons'>Desarrollador de Software</h1>
            <ul className='flex items-center'>
              <li>
                <GoFile />
              </li>
              <li>
                <a href='#' className='bg-cyan-300 text-black px-4 py-2 rounded-md ml-5'>CV</a>       
              </li> 
            </ul>  
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-4xl py-2 text-teal-500 font-medium'>Alejandro Ramos</h2>
            <h3 className='text-2xl py-2'>Full Stack Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-600'>Soy un desarrollador de software nacido y criado en Ushuaia. Egresé de un bootcamp en JavaScript brindado por
            Plataforma 5. </p>
          </div>
          <div className='text-4xl flex justify-center gap-16 py-3 text-gray-700'>
            <BsLinkedin/>
            <BsGithub />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={Avatar} alt="avatar" layout='fill' objectFit='cover' />
          </div>
        </section>
        <div>
          <h3 className='text-3xl py-1'>Servivios que ofrecemos</h3>
          <p className='text-md py-2 leading-8 text-gray-700'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor 
                <span className='text-teal-700'> incididunt </span>ut labore et dolore <span className='text-teal-700'>magna aliqua</span>. Ut enim ad minim 
                veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit 
                in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
          </p>
          <p className='text-md py-2 leading-8 text-gray-700'> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor .
          </p>
        </div>
        <div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <Image src={Movies} alt="App Pelis" width={250} height={200}/>
            <h3 className='text-lg font-medium pt-8 pb-2'>App de Peliculas</h3>
            <p className='py-2'>Breve descripcion de la aplicacion sin mencionar las tecnologias</p>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <Image src={Vaca} alt="App Vaca" width={250} height={200}/>
            <h3 className='text-lg font-medium pt-8 pb-2'>App de Peliculas</h3>
            <p className='py-2'>Breve descripcion de la aplicacion sin mencionar las tecnologias</p>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <Image src={Inmobiliaria} alt="App Inmobiliaria" width={250} height={200}/>
            <h3 className='text-lg font-medium pt-8 pb-2'>App de Peliculas</h3>
            <p className='py-2'>Breve descripcion de la aplicacion sin mencionar las tecnologias</p>
          </div>
        </div>
      </main>
    </div>
    </>
  )
}
