import React, { useState } from 'react';
import Head from 'next/head' ;

import { BsLinkedin , BsGithub} from "react-icons/bs";
import {IoIosCloudyNight} from "react-icons/io";
import { DiGit,DiHtml5,DiJsBadge,DiLinux,DiNodejs,DiPostgresql,DiReact} from "react-icons/di";

import Image from 'next/image';
import Avatar from '../public/myAvatar sinfondo.png';
import Movies from '../public/movies.png';
import Vaca from '../public/vaca-chocha.png';
import Inmobiliaria from '../public/inmo.png';
import Farmacia from '../public/farmacia.png';
import Logo from '../public/LogoPorta.png';


export default function Home() {
  
  const [darkMode,setDarkMode] = useState(false);
  const [lightMode,setLightMode] = useState(false);

  return (
    <>
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Portfolio Alejandro Ramos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/portfolio.svg" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-800'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <Image src={Logo} className='cursor-pointer w-60 h-50'/>
            <ul className='flex items-center'>
              <li>
                <IoIosCloudyNight onClick={()=>setDarkMode(!darkMode)} className='cursor-pointer text-3xl'/>
              </li>
              <li>
                <a href='https://drive.google.com/file/d/1S2QF2Bz7mYWqRT28bAI1NFRL_pdcjIOJ/view?usp=share_link' download >
                  <button className='bg-cyan-300 text-black px-8 py-5 rounded-md ml-5'>CV</button>
                </a>       
              </li> 
            </ul>  
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-4xl py-2 text-teal-500 font-medium md:text-6xl'>Alejandro Ramos</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Desarrollador Full Stack</h3>
            <p className='text-md py-5 leading-8 text-gray-600 md:text-xl'>Soy un programador nacido y criado en Ushuaia. De joven me interesé por la Informática y
            la Programación, pasando por educación secundaria y universidad. La vida me llevo a trabajar varios años en fábrica de electrodómesticos, decidí volver a mis raíces
            e ingresé a un bootcamp en JavaScript brindado por Plataforma 5.<br />Sigo formándome día a día para alcanzar mis metas como desarrollador de software.</p>
          </div>
          <div className='text-4xl flex justify-center gap-16 py-3 text-gray-700'>
            <BsLinkedin className='cursor-pointer' onClick={event =>  window.location.href='https://www.linkedin.com/in/alejandro-ramos-/'}/>
            <BsGithub className='cursor-pointer' onClick={event =>  window.location.href='https://github.com/ale336'}/>
          </div>
          <div className='relative mx-auto my-8 bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={Avatar} alt="avatar"  />
          </div>
        </section>
        <div className='text-6xl flex space-x-4 ... md:px-20'>
          <DiGit />
          <DiHtml5 />
          <DiJsBadge/>
          <DiLinux />
          <DiNodejs />
          <DiPostgresql />
          <DiReact />
          {/* <h3 className='text-3xl py-1'>Servivios que ofrecemos</h3>
          <p className='text-md py-2 leading-8 text-gray-700'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor 
                <span className='text-teal-700'> incididunt </span>ut labore et dolore <span className='text-teal-700'>magna aliqua</span>. Ut enim ad minim 
                veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit 
                in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
          </p>
          <p className='text-md py-2 leading-8 text-gray-700'> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.</p> */}
        </div>
        <div className='lg:flex gap-10'>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white cursor-pointer'>
            <Image src={Movies} alt="App Pelis" width={250} height={200} />
            <h3 className='text-lg font-medium pt-8 pb-2'>Movie App</h3>
            <p className='py-2'>Breve descripcion de la aplicacion sin mencionar las tecnologias</p>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white cursor-pointer'>
            <Image src={Vaca} alt="App Vaca" width={270} height={230}/>
            <h3 className='text-lg font-medium pt-8 pb-2'>E-commerce Dietética "Vaca Chocha"</h3>
            <p className='py-2'>Breve descripcion de la aplicacion sin mencionar las tecnologias</p>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white cursor-pointer'>
            <Image src={Inmobiliaria} alt="App Inmobiliaria" width={400} height={500}/>
            <h3 className='text-lg font-medium pt-8 pb-2'>Inmobiliaria Mejor Vivir</h3>
            <p className='py-2'>Breve descripcion de la aplicacion sin mencionar las tecnologias</p>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white cursor-pointer'>
            <Image src={Farmacia} alt="App Pharmacy" width={250} height={150}/>
            <h3 className='text-lg font-medium pt-8 pb-2'>E-commerce Farmacia</h3>
            <p className='py-2'>Breve descripcion de la aplicacion sin mencionar las tecnologias</p>
          </div>

        </div>
      </main>
    </div>
    </>
  )
}
